# https://taskfile.dev

version: "3"

vars:
  PYTHON_FILES: src tests

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task --list-all

  # Pre-commit hooks
  pre-commit:
    desc: Run all pre-commit hooks on all files
    cmds:
      - pre-commit run --all-files

  pre-commit:install:
    desc: Install pre-commit hooks
    cmds:
      - pre-commit install --install-hooks

  # Ruff linting and formatting
  ruff:
    desc: Run ruff check with fixes and format
    cmds:
      - task: ruff:check
      - task: ruff:format

  ruff:check:
    desc: Run ruff linter with auto-fix
    cmds:
      - uv run ruff check --fix {{.PYTHON_FILES}}

  ruff:format:
    desc: Run ruff formatter
    cmds:
      - uv run ruff format {{.PYTHON_FILES}}

  # Type checking
  mypy:
    desc: Run mypy type checker
    cmds:
      - uv run mypy

  # Pyproject formatting
  pyproject-fmt:
    desc: Format pyproject.toml
    cmds:
      - uv run pyproject-fmt pyproject.toml

  # Testing
  test:
    desc: Run tests with coverage
    cmds:
      - uv run pytest --cov --cov-report=term-missing --cov-report=html

