# https://taskfile.dev

version: "3"

vars:
  PYTHON_FILES: src tests

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task --list-all

  # Pre-commit hooks
  pre-commit:
    desc: Run all pre-commit hooks on all files
    cmds:
      - uv run pre-commit run --all-files

  pre-commit:install:
    desc: Install pre-commit hooks
    cmds:
      - uv run pre-commit install --install-hooks

  # Ruff linting and formatting
  ruff:
    desc: Run ruff check with fixes and format
    cmds:
      - task: ruff:check
      - task: ruff:format

  ruff:check:
    desc: Run ruff linter with auto-fix
    cmds:
      - uv run ruff check --fix {{.PYTHON_FILES}}

  ruff:format:
    desc: Run ruff formatter
    cmds:
      - uv run ruff format {{.PYTHON_FILES}}

  # Type checking
  mypy:
    desc: Run mypy type checker
    cmds:
      - uv run mypy

  # Pyproject formatting
  pyproject-fmt:
    desc: Format pyproject.toml
    cmds:
      - uv run pyproject-fmt pyproject.toml

  # Testing
  test:
    desc: Run tests with coverage
    cmds:
      - uv run pytest --cov --cov-report=term-missing --cov-report=html

  # Dependencies
  outdated:
    desc: Check for outdated dependencies
    ignore_error: true
    cmds:
      - uv tree --depth=1 --outdated | grep latest

  update:
    desc: Update all dependencies
    cmds:
      - uv sync --all-groups --all-extras
      - uv lock --upgrade
      - uv run pre-commit autoupdate

  # Generate docs
  docs:
    desc: Generate docs
    cmds:
      - uv run mkdocs build

  # Build the project
  build:
    desc: Build the project
    cmds:
      - uv build --wheel --sdist
