name: Perform code checks

on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true
  push:

jobs:
  # Code checks
  python_lint:
    uses: ./.github/workflows/python_lint.yml
  typing:
    uses: ./.github/workflows/type_check.yml
  tests:
    needs: [python_lint, typing]
    uses: ./.github/workflows/tests.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  # Text formatting checks
  md_lint:
    uses: ./.github/workflows/md_lint.yml
  codespell:
    uses: ./.github/workflows/codespell.yml
  # TODO(Vlad): Implement docs build checks
  # docs_build:
  #   needs: [md_lint, codespell]
  #   uses: ./.github/workflows/docs_build.yml
