name: Perform code checks

on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true
  push:

jobs:
  # TODO(Vlad): Add markdown linting checks
  python_lint:
    uses: ./.github/workflows/python_lint.yml
  typing:
    uses: ./.github/workflows/type_check.yml
  tests:
    needs: [python_lint, typing]
    uses: ./.github/workflows/tests.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
